/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const ProfileLazyImport = createFileRoute('/profile')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const CarsIndexLazyImport = createFileRoute('/cars/')()
const AdminSpecsIndexLazyImport = createFileRoute('/admin/specs/')()
const AdminOptionsIndexLazyImport = createFileRoute('/admin/options/')()
const AdminManufacturesIndexLazyImport = createFileRoute(
  '/admin/manufactures/',
)()
const AdminCarsIndexLazyImport = createFileRoute('/admin/cars/')()
const AdminSpecsCreateLazyImport = createFileRoute('/admin/specs/create')()
const AdminSpecsIdLazyImport = createFileRoute('/admin/specs/$id')()
const AdminOptionsCreateLazyImport = createFileRoute('/admin/options/create')()
const AdminOptionsIdLazyImport = createFileRoute('/admin/options/$id')()
const AdminManufacturesCreateLazyImport = createFileRoute(
  '/admin/manufactures/create',
)()
const AdminManufacturesIdLazyImport = createFileRoute(
  '/admin/manufactures/$id',
)()
const AdminCarsNextFormLazyImport = createFileRoute('/admin/cars/next-form')()
const AdminCarsNextCreateLazyImport = createFileRoute(
  '/admin/cars/next-create',
)()
const AdminCarsCreateLazyImport = createFileRoute('/admin/cars/create')()
const AdminCarsIdLazyImport = createFileRoute('/admin/cars/$id')()
const AdminSpecsEditIdLazyImport = createFileRoute('/admin/specs/edit/$id')()
const AdminOptionsEditIdLazyImport = createFileRoute(
  '/admin/options/edit/$id',
)()
const AdminManufacturesEditIdLazyImport = createFileRoute(
  '/admin/manufactures/edit/$id',
)()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CarsIndexLazyRoute = CarsIndexLazyImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cars/index.lazy').then((d) => d.Route))

const AdminSpecsIndexLazyRoute = AdminSpecsIndexLazyImport.update({
  id: '/admin/specs/',
  path: '/admin/specs/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/specs/index.lazy').then((d) => d.Route),
)

const AdminOptionsIndexLazyRoute = AdminOptionsIndexLazyImport.update({
  id: '/admin/options/',
  path: '/admin/options/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/options/index.lazy').then((d) => d.Route),
)

const AdminManufacturesIndexLazyRoute = AdminManufacturesIndexLazyImport.update(
  {
    id: '/admin/manufactures/',
    path: '/admin/manufactures/',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/admin/manufactures/index.lazy').then((d) => d.Route),
)

const AdminCarsIndexLazyRoute = AdminCarsIndexLazyImport.update({
  id: '/admin/cars/',
  path: '/admin/cars/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/index.lazy').then((d) => d.Route),
)

const AdminSpecsCreateLazyRoute = AdminSpecsCreateLazyImport.update({
  id: '/admin/specs/create',
  path: '/admin/specs/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/specs/create.lazy').then((d) => d.Route),
)

const AdminSpecsIdLazyRoute = AdminSpecsIdLazyImport.update({
  id: '/admin/specs/$id',
  path: '/admin/specs/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/specs/$id.lazy').then((d) => d.Route),
)

const AdminOptionsCreateLazyRoute = AdminOptionsCreateLazyImport.update({
  id: '/admin/options/create',
  path: '/admin/options/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/options/create.lazy').then((d) => d.Route),
)

const AdminOptionsIdLazyRoute = AdminOptionsIdLazyImport.update({
  id: '/admin/options/$id',
  path: '/admin/options/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/options/$id.lazy').then((d) => d.Route),
)

const AdminManufacturesCreateLazyRoute =
  AdminManufacturesCreateLazyImport.update({
    id: '/admin/manufactures/create',
    path: '/admin/manufactures/create',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/admin/manufactures/create.lazy').then((d) => d.Route),
  )

const AdminManufacturesIdLazyRoute = AdminManufacturesIdLazyImport.update({
  id: '/admin/manufactures/$id',
  path: '/admin/manufactures/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/manufactures/$id.lazy').then((d) => d.Route),
)

const AdminCarsNextFormLazyRoute = AdminCarsNextFormLazyImport.update({
  id: '/admin/cars/next-form',
  path: '/admin/cars/next-form',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/next-form.lazy').then((d) => d.Route),
)

const AdminCarsNextCreateLazyRoute = AdminCarsNextCreateLazyImport.update({
  id: '/admin/cars/next-create',
  path: '/admin/cars/next-create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/next-create.lazy').then((d) => d.Route),
)

const AdminCarsCreateLazyRoute = AdminCarsCreateLazyImport.update({
  id: '/admin/cars/create',
  path: '/admin/cars/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/create.lazy').then((d) => d.Route),
)

const AdminCarsIdLazyRoute = AdminCarsIdLazyImport.update({
  id: '/admin/cars/$id',
  path: '/admin/cars/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/$id.lazy').then((d) => d.Route),
)

const AdminSpecsEditIdLazyRoute = AdminSpecsEditIdLazyImport.update({
  id: '/admin/specs/edit/$id',
  path: '/admin/specs/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/specs/edit/$id.lazy').then((d) => d.Route),
)

const AdminOptionsEditIdLazyRoute = AdminOptionsEditIdLazyImport.update({
  id: '/admin/options/edit/$id',
  path: '/admin/options/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/options/edit/$id.lazy').then((d) => d.Route),
)

const AdminManufacturesEditIdLazyRoute =
  AdminManufacturesEditIdLazyImport.update({
    id: '/admin/manufactures/edit/$id',
    path: '/admin/manufactures/edit/$id',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/admin/manufactures/edit/$id.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/$id': {
      id: '/admin/cars/$id'
      path: '/admin/cars/$id'
      fullPath: '/admin/cars/$id'
      preLoaderRoute: typeof AdminCarsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/create': {
      id: '/admin/cars/create'
      path: '/admin/cars/create'
      fullPath: '/admin/cars/create'
      preLoaderRoute: typeof AdminCarsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/next-create': {
      id: '/admin/cars/next-create'
      path: '/admin/cars/next-create'
      fullPath: '/admin/cars/next-create'
      preLoaderRoute: typeof AdminCarsNextCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/next-form': {
      id: '/admin/cars/next-form'
      path: '/admin/cars/next-form'
      fullPath: '/admin/cars/next-form'
      preLoaderRoute: typeof AdminCarsNextFormLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufactures/$id': {
      id: '/admin/manufactures/$id'
      path: '/admin/manufactures/$id'
      fullPath: '/admin/manufactures/$id'
      preLoaderRoute: typeof AdminManufacturesIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufactures/create': {
      id: '/admin/manufactures/create'
      path: '/admin/manufactures/create'
      fullPath: '/admin/manufactures/create'
      preLoaderRoute: typeof AdminManufacturesCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/options/$id': {
      id: '/admin/options/$id'
      path: '/admin/options/$id'
      fullPath: '/admin/options/$id'
      preLoaderRoute: typeof AdminOptionsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/options/create': {
      id: '/admin/options/create'
      path: '/admin/options/create'
      fullPath: '/admin/options/create'
      preLoaderRoute: typeof AdminOptionsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/specs/$id': {
      id: '/admin/specs/$id'
      path: '/admin/specs/$id'
      fullPath: '/admin/specs/$id'
      preLoaderRoute: typeof AdminSpecsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/specs/create': {
      id: '/admin/specs/create'
      path: '/admin/specs/create'
      fullPath: '/admin/specs/create'
      preLoaderRoute: typeof AdminSpecsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/': {
      id: '/admin/cars/'
      path: '/admin/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminCarsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufactures/': {
      id: '/admin/manufactures/'
      path: '/admin/manufactures'
      fullPath: '/admin/manufactures'
      preLoaderRoute: typeof AdminManufacturesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/options/': {
      id: '/admin/options/'
      path: '/admin/options'
      fullPath: '/admin/options'
      preLoaderRoute: typeof AdminOptionsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/specs/': {
      id: '/admin/specs/'
      path: '/admin/specs'
      fullPath: '/admin/specs'
      preLoaderRoute: typeof AdminSpecsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufactures/edit/$id': {
      id: '/admin/manufactures/edit/$id'
      path: '/admin/manufactures/edit/$id'
      fullPath: '/admin/manufactures/edit/$id'
      preLoaderRoute: typeof AdminManufacturesEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/options/edit/$id': {
      id: '/admin/options/edit/$id'
      path: '/admin/options/edit/$id'
      fullPath: '/admin/options/edit/$id'
      preLoaderRoute: typeof AdminOptionsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/specs/edit/$id': {
      id: '/admin/specs/edit/$id'
      path: '/admin/specs/edit/$id'
      fullPath: '/admin/specs/edit/$id'
      preLoaderRoute: typeof AdminSpecsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/cars': typeof CarsIndexLazyRoute
  '/admin/cars/$id': typeof AdminCarsIdLazyRoute
  '/admin/cars/create': typeof AdminCarsCreateLazyRoute
  '/admin/cars/next-create': typeof AdminCarsNextCreateLazyRoute
  '/admin/cars/next-form': typeof AdminCarsNextFormLazyRoute
  '/admin/manufactures/$id': typeof AdminManufacturesIdLazyRoute
  '/admin/manufactures/create': typeof AdminManufacturesCreateLazyRoute
  '/admin/options/$id': typeof AdminOptionsIdLazyRoute
  '/admin/options/create': typeof AdminOptionsCreateLazyRoute
  '/admin/specs/$id': typeof AdminSpecsIdLazyRoute
  '/admin/specs/create': typeof AdminSpecsCreateLazyRoute
  '/admin/cars': typeof AdminCarsIndexLazyRoute
  '/admin/manufactures': typeof AdminManufacturesIndexLazyRoute
  '/admin/options': typeof AdminOptionsIndexLazyRoute
  '/admin/specs': typeof AdminSpecsIndexLazyRoute
  '/admin/manufactures/edit/$id': typeof AdminManufacturesEditIdLazyRoute
  '/admin/options/edit/$id': typeof AdminOptionsEditIdLazyRoute
  '/admin/specs/edit/$id': typeof AdminSpecsEditIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/cars': typeof CarsIndexLazyRoute
  '/admin/cars/$id': typeof AdminCarsIdLazyRoute
  '/admin/cars/create': typeof AdminCarsCreateLazyRoute
  '/admin/cars/next-create': typeof AdminCarsNextCreateLazyRoute
  '/admin/cars/next-form': typeof AdminCarsNextFormLazyRoute
  '/admin/manufactures/$id': typeof AdminManufacturesIdLazyRoute
  '/admin/manufactures/create': typeof AdminManufacturesCreateLazyRoute
  '/admin/options/$id': typeof AdminOptionsIdLazyRoute
  '/admin/options/create': typeof AdminOptionsCreateLazyRoute
  '/admin/specs/$id': typeof AdminSpecsIdLazyRoute
  '/admin/specs/create': typeof AdminSpecsCreateLazyRoute
  '/admin/cars': typeof AdminCarsIndexLazyRoute
  '/admin/manufactures': typeof AdminManufacturesIndexLazyRoute
  '/admin/options': typeof AdminOptionsIndexLazyRoute
  '/admin/specs': typeof AdminSpecsIndexLazyRoute
  '/admin/manufactures/edit/$id': typeof AdminManufacturesEditIdLazyRoute
  '/admin/options/edit/$id': typeof AdminOptionsEditIdLazyRoute
  '/admin/specs/edit/$id': typeof AdminSpecsEditIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/cars/': typeof CarsIndexLazyRoute
  '/admin/cars/$id': typeof AdminCarsIdLazyRoute
  '/admin/cars/create': typeof AdminCarsCreateLazyRoute
  '/admin/cars/next-create': typeof AdminCarsNextCreateLazyRoute
  '/admin/cars/next-form': typeof AdminCarsNextFormLazyRoute
  '/admin/manufactures/$id': typeof AdminManufacturesIdLazyRoute
  '/admin/manufactures/create': typeof AdminManufacturesCreateLazyRoute
  '/admin/options/$id': typeof AdminOptionsIdLazyRoute
  '/admin/options/create': typeof AdminOptionsCreateLazyRoute
  '/admin/specs/$id': typeof AdminSpecsIdLazyRoute
  '/admin/specs/create': typeof AdminSpecsCreateLazyRoute
  '/admin/cars/': typeof AdminCarsIndexLazyRoute
  '/admin/manufactures/': typeof AdminManufacturesIndexLazyRoute
  '/admin/options/': typeof AdminOptionsIndexLazyRoute
  '/admin/specs/': typeof AdminSpecsIndexLazyRoute
  '/admin/manufactures/edit/$id': typeof AdminManufacturesEditIdLazyRoute
  '/admin/options/edit/$id': typeof AdminOptionsEditIdLazyRoute
  '/admin/specs/edit/$id': typeof AdminSpecsEditIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/cars'
    | '/admin/cars/$id'
    | '/admin/cars/create'
    | '/admin/cars/next-create'
    | '/admin/cars/next-form'
    | '/admin/manufactures/$id'
    | '/admin/manufactures/create'
    | '/admin/options/$id'
    | '/admin/options/create'
    | '/admin/specs/$id'
    | '/admin/specs/create'
    | '/admin/cars'
    | '/admin/manufactures'
    | '/admin/options'
    | '/admin/specs'
    | '/admin/manufactures/edit/$id'
    | '/admin/options/edit/$id'
    | '/admin/specs/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/cars'
    | '/admin/cars/$id'
    | '/admin/cars/create'
    | '/admin/cars/next-create'
    | '/admin/cars/next-form'
    | '/admin/manufactures/$id'
    | '/admin/manufactures/create'
    | '/admin/options/$id'
    | '/admin/options/create'
    | '/admin/specs/$id'
    | '/admin/specs/create'
    | '/admin/cars'
    | '/admin/manufactures'
    | '/admin/options'
    | '/admin/specs'
    | '/admin/manufactures/edit/$id'
    | '/admin/options/edit/$id'
    | '/admin/specs/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/cars/'
    | '/admin/cars/$id'
    | '/admin/cars/create'
    | '/admin/cars/next-create'
    | '/admin/cars/next-form'
    | '/admin/manufactures/$id'
    | '/admin/manufactures/create'
    | '/admin/options/$id'
    | '/admin/options/create'
    | '/admin/specs/$id'
    | '/admin/specs/create'
    | '/admin/cars/'
    | '/admin/manufactures/'
    | '/admin/options/'
    | '/admin/specs/'
    | '/admin/manufactures/edit/$id'
    | '/admin/options/edit/$id'
    | '/admin/specs/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  CarsIndexLazyRoute: typeof CarsIndexLazyRoute
  AdminCarsIdLazyRoute: typeof AdminCarsIdLazyRoute
  AdminCarsCreateLazyRoute: typeof AdminCarsCreateLazyRoute
  AdminCarsNextCreateLazyRoute: typeof AdminCarsNextCreateLazyRoute
  AdminCarsNextFormLazyRoute: typeof AdminCarsNextFormLazyRoute
  AdminManufacturesIdLazyRoute: typeof AdminManufacturesIdLazyRoute
  AdminManufacturesCreateLazyRoute: typeof AdminManufacturesCreateLazyRoute
  AdminOptionsIdLazyRoute: typeof AdminOptionsIdLazyRoute
  AdminOptionsCreateLazyRoute: typeof AdminOptionsCreateLazyRoute
  AdminSpecsIdLazyRoute: typeof AdminSpecsIdLazyRoute
  AdminSpecsCreateLazyRoute: typeof AdminSpecsCreateLazyRoute
  AdminCarsIndexLazyRoute: typeof AdminCarsIndexLazyRoute
  AdminManufacturesIndexLazyRoute: typeof AdminManufacturesIndexLazyRoute
  AdminOptionsIndexLazyRoute: typeof AdminOptionsIndexLazyRoute
  AdminSpecsIndexLazyRoute: typeof AdminSpecsIndexLazyRoute
  AdminManufacturesEditIdLazyRoute: typeof AdminManufacturesEditIdLazyRoute
  AdminOptionsEditIdLazyRoute: typeof AdminOptionsEditIdLazyRoute
  AdminSpecsEditIdLazyRoute: typeof AdminSpecsEditIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  CarsIndexLazyRoute: CarsIndexLazyRoute,
  AdminCarsIdLazyRoute: AdminCarsIdLazyRoute,
  AdminCarsCreateLazyRoute: AdminCarsCreateLazyRoute,
  AdminCarsNextCreateLazyRoute: AdminCarsNextCreateLazyRoute,
  AdminCarsNextFormLazyRoute: AdminCarsNextFormLazyRoute,
  AdminManufacturesIdLazyRoute: AdminManufacturesIdLazyRoute,
  AdminManufacturesCreateLazyRoute: AdminManufacturesCreateLazyRoute,
  AdminOptionsIdLazyRoute: AdminOptionsIdLazyRoute,
  AdminOptionsCreateLazyRoute: AdminOptionsCreateLazyRoute,
  AdminSpecsIdLazyRoute: AdminSpecsIdLazyRoute,
  AdminSpecsCreateLazyRoute: AdminSpecsCreateLazyRoute,
  AdminCarsIndexLazyRoute: AdminCarsIndexLazyRoute,
  AdminManufacturesIndexLazyRoute: AdminManufacturesIndexLazyRoute,
  AdminOptionsIndexLazyRoute: AdminOptionsIndexLazyRoute,
  AdminSpecsIndexLazyRoute: AdminSpecsIndexLazyRoute,
  AdminManufacturesEditIdLazyRoute: AdminManufacturesEditIdLazyRoute,
  AdminOptionsEditIdLazyRoute: AdminOptionsEditIdLazyRoute,
  AdminSpecsEditIdLazyRoute: AdminSpecsEditIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/login",
        "/profile",
        "/register",
        "/cars/",
        "/admin/cars/$id",
        "/admin/cars/create",
        "/admin/cars/next-create",
        "/admin/cars/next-form",
        "/admin/manufactures/$id",
        "/admin/manufactures/create",
        "/admin/options/$id",
        "/admin/options/create",
        "/admin/specs/$id",
        "/admin/specs/create",
        "/admin/cars/",
        "/admin/manufactures/",
        "/admin/options/",
        "/admin/specs/",
        "/admin/manufactures/edit/$id",
        "/admin/options/edit/$id",
        "/admin/specs/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/profile": {
      "filePath": "profile.lazy.jsx"
    },
    "/register": {
      "filePath": "register.lazy.jsx"
    },
    "/cars/": {
      "filePath": "cars/index.lazy.jsx"
    },
    "/admin/cars/$id": {
      "filePath": "admin/cars/$id.lazy.jsx"
    },
    "/admin/cars/create": {
      "filePath": "admin/cars/create.lazy.jsx"
    },
    "/admin/cars/next-create": {
      "filePath": "admin/cars/next-create.lazy.jsx"
    },
    "/admin/cars/next-form": {
      "filePath": "admin/cars/next-form.lazy.jsx"
    },
    "/admin/manufactures/$id": {
      "filePath": "admin/manufactures/$id.lazy.jsx"
    },
    "/admin/manufactures/create": {
      "filePath": "admin/manufactures/create.lazy.jsx"
    },
    "/admin/options/$id": {
      "filePath": "admin/options/$id.lazy.jsx"
    },
    "/admin/options/create": {
      "filePath": "admin/options/create.lazy.jsx"
    },
    "/admin/specs/$id": {
      "filePath": "admin/specs/$id.lazy.jsx"
    },
    "/admin/specs/create": {
      "filePath": "admin/specs/create.lazy.jsx"
    },
    "/admin/cars/": {
      "filePath": "admin/cars/index.lazy.jsx"
    },
    "/admin/manufactures/": {
      "filePath": "admin/manufactures/index.lazy.jsx"
    },
    "/admin/options/": {
      "filePath": "admin/options/index.lazy.jsx"
    },
    "/admin/specs/": {
      "filePath": "admin/specs/index.lazy.jsx"
    },
    "/admin/manufactures/edit/$id": {
      "filePath": "admin/manufactures/edit/$id.lazy.jsx"
    },
    "/admin/options/edit/$id": {
      "filePath": "admin/options/edit/$id.lazy.jsx"
    },
    "/admin/specs/edit/$id": {
      "filePath": "admin/specs/edit/$id.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
